spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persondb
    username: root
    password: Chinnunoor@786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
    port: 8080